// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: vamvbpnarwjmlqveybjf

class SupabaseConfig {
  static const String supabaseUrl = 'https://vamvbpnarwjmlqveybjf.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbXZicG5hcndqbWxxdmV5YmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzcxMTIsImV4cCI6MjA3MTc1MzExMn0.SFRiN7mYG_LDSThK7YdLqBim1ul2-79A_U6nZacFktU';
}
